"use client";
/* eslint-disable @next/next/no-img-element */
import { NexusBranch, NexusBranchEvent, SelectedRecord, TimelineEvent } from "@/lib/types";
type Props = { record: SelectedRecord | null; image?: string; loading: boolean; imageError?: string; onImage: (force?: boolean) => void; onLoadDemo: () => void };
const List = ({ title, items }: { title: string; items: string[] }) => <section className="mt-5"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-mist">{title}</p><ol className="mt-2 space-y-1 text-xs leading-5 text-[#bdc6bf]">{items.map((item, index) => <li key={`${item}-${index}`}><span className="mr-2 font-mono text-signal">{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></section>;
function ImagePlate({ image, loading, title }: { image?: string; loading: boolean; title: string }) { return <div className="mt-7 aspect-[3/2] overflow-hidden border border-white/10 bg-[#0a0e11]">{image ? <img src={image} alt={`Generated record illustration for ${title}`} className="h-full w-full object-cover"/> : <div className="flex h-full flex-col items-center justify-center text-center"><span className="mb-3 h-8 w-8 animate-pulse rounded-full border border-signal/60"/><p className="font-mono text-[9px] uppercase tracking-[.16em] text-mist">{loading ? "Temporal reconstruction in progress" : "Visual record unavailable"}</p></div>}</div>; }
function Shell({ children, recordType }: { children: React.ReactNode; recordType: string }) { return <aside className="min-h-[620px] overflow-y-auto border-l border-white/10 bg-panel p-7 pb-28 lg:h-[calc(100vh-4rem)]"><p className="font-mono text-[10px] uppercase tracking-[.25em] text-signal">Record / {recordType}</p>{children}</aside>; }
function PrimeRecord({ event, image, loading, imageError, onImage, onLoadDemo }: { event: TimelineEvent; image?: string; loading: boolean; imageError?: string; onImage: () => void; onLoadDemo: () => void }) { return <Shell recordType="prime"><p className="mt-7 font-mono text-5xl text-[#f1a643]">{event.year}</p><h1 className="mt-3 text-2xl font-medium text-[#f5f4ee]">{event.title}</h1><ImagePlate image={image} loading={loading} title={event.title}/>{imageError && <p className="mt-3 text-xs text-red-300">{imageError}</p>}<p className="mt-5 text-sm leading-7 text-[#b9c1bc]">{event.description}</p><div className="my-6 h-px bg-white/10"/><List title="Actual outcome" items={[event.actualOutcome]}/><List title="Causal dependencies" items={event.causalDependencies}/><List title="Historical impact" items={event.historicalImpact}/><Domains domains={event.domains}/><div className="mt-4 grid gap-2"><button onClick={onLoadDemo} className="border border-white/20 px-3 py-3 font-mono text-[10px] uppercase tracking-[.14em] text-[#dbe2da] hover:border-signal">Load Demo Nexus</button><button onClick={onImage} disabled={loading} className="border border-signal/70 px-3 py-3 font-mono text-[10px] uppercase tracking-[.14em] text-signal disabled:opacity-50">{loading ? "Reconstructing..." : image ? "Regenerate Image" : "Generate Record Image"}</button></div></Shell>; }
function Domains({ domains }: { domains: string[] }) { return <><p className="mt-5 font-mono text-[9px] uppercase tracking-[.2em] text-mist">Domains</p><div className="mt-2 flex flex-wrap gap-2">{domains.map((domain) => <span key={domain} className="border border-white/15 px-2 py-1 font-mono text-[9px] uppercase text-[#c6d0c9]">{domain}</span>)}</div></>; }
function BranchRecord({ event, branch, image, loading, imageError, onImage }: { event: NexusBranchEvent; branch: NexusBranch; image?: string; loading: boolean; imageError?: string; onImage: () => void }) { return <Shell recordType="branch"><p className="mt-2 font-mono text-[9px] uppercase tracking-[.15em] text-cyan-300">Speculative alternate timeline · {branch.branchName}</p><p className="mt-7 font-mono text-5xl text-[#f1a643]">{event.year}</p><h1 className="mt-3 text-2xl font-medium text-[#f5f4ee]">{event.title}</h1><p className="mt-2 font-mono text-[10px] uppercase tracking-[.16em] text-[#8bd9f7]">{event.phase.replaceAll("_", " ")} · confidence {event.confidence}</p><ImagePlate image={image} loading={loading} title={event.title}/>{imageError && <p className="mt-3 text-xs text-red-300">{imageError}</p>}<p className="mt-5 text-sm leading-7 text-[#b9c1bc]">{event.description}</p><div className="my-6 h-px bg-white/10"/><List title="Causal mechanism" items={[event.causalMechanism]}/><List title="Caused by" items={event.causedBy.length ? event.causedBy : ["Divergence record"]}/><List title="Convergence pressures" items={branch.counterforces}/><List title="Historical continuities" items={branch.historicalContinuities}/><Domains domains={event.affectedDomains}/><button onClick={onImage} disabled={loading} className="mt-4 w-full border border-signal/70 px-3 py-3 font-mono text-[10px] uppercase tracking-[.14em] text-signal disabled:opacity-50">{loading ? "Reconstructing..." : image ? "Regenerate Image" : "Reconstruct Image"}</button></Shell>; }
export function EventDetailPanel({ record, image, loading, imageError, onImage, onLoadDemo }: Props) { if (!record) return <aside className="flex min-h-[620px] items-center justify-center overflow-y-auto border-l border-white/10 bg-panel p-10 text-center font-mono text-xs uppercase tracking-[.18em] text-mist lg:h-[calc(100vh-4rem)]">Select a temporal record<br/>to inspect</aside>; return record.kind === "prime" ? <PrimeRecord event={record.event} image={image} loading={loading} imageError={imageError} onImage={() => onImage(Boolean(image))} onLoadDemo={onLoadDemo}/> : <BranchRecord event={record.event} branch={record.branch} image={image} loading={loading} imageError={imageError} onImage={() => onImage(Boolean(image))}/>; }
