"use client";
/* eslint-disable @next/next/no-img-element */
import { motion } from "framer-motion";
import { MouseEvent, useState } from "react";
import { NexusBranch, NexusBranchEvent, TimelineEvent } from "@/lib/types";
import { calculateCanvasHeight, calculateCanvasWidth, createBranchLayout, positionPrimeEvents, PRIME_X } from "@/lib/timeline-layout";

type Props = { events: TimelineEvent[]; branches: NexusBranch[]; selectedId?: string; pruningBranchKey?: string; onPrimeSelect: (event: TimelineEvent) => void; onBranchSelect: (event: NexusBranchEvent, branch: NexusBranch) => void };
type Preview = { title: string; image?: string; x: number; y: number };
const colors = ["#7ce8ff", "#a7f3d0", "#b99aff"];
const phaseCode: Record<NexusBranchEvent["phase"], string> = { divergence: "DIV", immediate: "IMD", short_term: "S-TERM", medium_term: "M-TERM", long_term: "L-TERM", present_day: "PRESENT" };

export function TimelineCanvas({ events, branches, selectedId, pruningBranchKey, onPrimeSelect, onBranchSelect }: Props) {
  const [preview, setPreview] = useState<Preview>(); const prime = positionPrimeEvents(events); const height = calculateCanvasHeight(events, branches); const width = calculateCanvasWidth(branches.length);
  function showPreview(event: TimelineEvent | NexusBranchEvent, pointer: MouseEvent<HTMLButtonElement>) { let image: string | undefined; try { image = JSON.parse(localStorage.getItem("nexus-images-v1") ?? "{}")[event.id]; } catch { /* Preview remains text-only until an illustration exists. */ } setPreview({ title: event.title, image, x: pointer.clientX + 18, y: pointer.clientY + 18 }); }
  return <section className="relative h-full min-h-[720px] overflow-auto border-r border-white/10 bg-[radial-gradient(circle_at_28%_28%,rgba(241,166,67,.08),transparent_27%)]" aria-label="Timeline map">
    <div className="absolute left-7 top-7 z-10 font-mono text-[10px] uppercase tracking-[.28em] text-mist">Chronology / prime record</div>
    <svg viewBox={`0 0 ${width} ${height}`} className="min-h-[720px] min-w-[700px]" style={{ width, height }} role="img" aria-label="Interactive prime timeline and speculative branches">
      <defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><filter id="aura"><feGaussianBlur stdDeviation="9" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="temporalStream" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#b99aff"/><stop offset=".42" stopColor="#7ce8ff"/><stop offset=".72" stopColor="#f7f1ff"/><stop offset="1" stopColor="#ff98d1"/></linearGradient><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M 24 0 L 0 0 0 24" fill="none" stroke="rgba(145,163,165,.10)" strokeWidth=".5"/></pattern></defs>
      <rect width={width} height={height} fill="url(#grid)"/><path d={`M ${PRIME_X} 70 V ${height - 50}`} stroke="rgba(104,190,255,.18)" strokeWidth="18" filter="url(#aura)"/><path d={`M ${PRIME_X} 70 V ${height - 50}`} stroke="rgba(212,221,216,.38)" strokeWidth="2"/><motion.path d={`M ${PRIME_X} 70 V ${height - 50}`} fill="none" stroke="url(#temporalStream)" strokeWidth="2.5" strokeDasharray="3 12" initial={{ strokeDashoffset: 0 }} animate={{ strokeDashoffset: -90 }} transition={{ duration: 3, ease: "linear", repeat: Infinity }}/>
      {branches.map((branch, index) => { const layout = createBranchLayout(branch, index, events); const color = colors[index]; const branchKey = `${branch.branchName}-${branch.anchorEventId}`; const pruning = pruningBranchKey === branchKey; return <motion.g key={branchKey} animate={pruning ? { opacity: [1, 1, 0], scale: [1, 1.06, .15] } : { opacity: 1, scale: 1 }} transition={{ duration: pruning ? .7 : .2 }}><motion.path d={layout.path} fill="none" stroke={color} strokeWidth="2" filter="url(#glow)" initial={{ pathLength: 0, opacity: 0 }} animate={{ pathLength: 1, opacity: 1 }} transition={{ duration: 1.4 }}/>{branch.events.map((event, eventIndex) => { const item = layout.events[eventIndex]; if (!item) return null; const active = selectedId === event.id; return <g key={event.id}><circle cx={item.x} cy={item.y} r={active ? 12 : 7} fill="#10151a" stroke={color} strokeWidth="2" filter={active ? "url(#glow)" : undefined}/><foreignObject x={item.x-14} y={item.y-14} width="28" height="28"><button onClick={() => onBranchSelect(event, branch)} onMouseEnter={(pointer) => showPreview(event, pointer)} onMouseLeave={() => setPreview(undefined)} aria-label={`${event.year}: ${event.title}, speculative ${phaseCode[event.phase]}`} className="h-7 w-7 rounded-full outline-none focus:ring-2 focus:ring-white"/></foreignObject><text x={item.x+18} y={item.y-3} fill={color} fontSize="10" fontFamily="monospace">{event.year} / {phaseCode[event.phase]}</text><text x={item.x+18} y={item.y+12} fill="#d3d8d2" fontSize="11">{event.title}</text></g>; })}</motion.g>; })}
      {prime.map((event) => { const active = selectedId === event.id; return <g key={event.id}>{active && <circle cx={event.x} cy={event.y} r="16" fill="none" stroke="#f1a643" opacity=".45" className="animate-pulse-signal"/>}<circle cx={event.x} cy={event.y} r={active ? 8 : 6} fill={active ? "#f1a643" : "#10151a"} stroke="#f1a643" strokeWidth="1.5" filter={active ? "url(#glow)" : undefined}/><foreignObject x={event.x-14} y={event.y-14} width="28" height="28"><button onClick={() => onPrimeSelect(event)} onMouseEnter={(pointer) => showPreview(event, pointer)} onMouseLeave={() => setPreview(undefined)} aria-label={`${event.year}: ${event.title}`} className="h-7 w-7 rounded-full outline-none focus:ring-2 focus:ring-white"/></foreignObject><text x={event.x+21} y={event.y-3} fill={active ? "#f4d09d" : "#a9b4b3"} fontSize="11" fontFamily="monospace">{event.year}</text><text x={event.x+67} y={event.y-3} fill={active ? "#f6f4ec" : "#d3d8d2"} fontSize="11">{event.title}</text></g>; })}
    </svg>
    {preview && <div className="pointer-events-none fixed z-[60] w-52 overflow-hidden border border-[#7ce8ff]/50 bg-[#071018] shadow-[0_0_25px_rgba(124,232,255,.25)]" style={{ left: preview.x, top: preview.y }}>{preview.image ? <img src={preview.image} alt="" className="h-28 w-full object-cover"/> : <div className="flex h-28 items-center justify-center bg-[#0b151d] font-mono text-[9px] uppercase tracking-[.16em] text-mist">No visual record</div>}<div className="border-t border-white/10 bg-[#06090b]/95 px-3 py-2"><p className="font-mono text-[8px] uppercase tracking-[.18em] text-[#7ce8ff]">Event record</p><p className="mt-1 text-xs text-[#f4f5ef]">{preview.title}</p></div></div>}
    <div className="absolute bottom-7 left-7 max-w-[260px] font-mono text-[9px] uppercase tracking-[.2em] text-mist">{events.length} fixed points / {branches.length} active branch{branches.length === 1 ? "" : "es"}<span className="mt-2 block normal-case tracking-normal text-[#74817f]">Hover a node to preview its visual record.</span></div>
  </section>;
}
