import { TimelineDomain, TimelineEvent } from "./types";

type Seed = Pick<TimelineEvent, "id" | "year" | "title" | "description" | "actualOutcome" | "domains" | "demoNexusPrompt" | "imagePrompt">;
const seeds: Seed[] = [
  { id: "evt-001", year: 1455, title: "Printing at Scale", description: "Movable-type printing demonstrates that written knowledge can be reproduced rapidly and consistently.", actualOutcome: "Mechanical printing expands books, religious texts, science and political argument across Europe.", domains: ["technology", "culture", "society"], demoNexusPrompt: "What if the first major printing workshop and all its technical records were destroyed before the method spread?", imagePrompt: "A fifteenth-century European printing workshop, wooden press, movable metal type, candlelight, cinematic archival realism, dark charcoal and amber tones, no readable text." },
  { id: "evt-001b", year: 1518, title: "The Dancing Plague", description: "In Strasbourg, groups of people dance for days in an episode still debated by historians.", actualOutcome: "The event remains a vivid record of how stress, belief, illness and public authority can interact in a crisis.", domains: ["culture", "medicine", "society"], demoNexusPrompt: "What if city officials had treated the Strasbourg dancing outbreak as a public-health emergency instead of organising music for it?", imagePrompt: "A 1518 Strasbourg street with anxious townspeople, musicians and civic officials observing an unusual public gathering, grounded cinematic archival realism, no readable text." },
  { id: "evt-002", year: 1796, title: "The Vaccination Principle", description: "An early vaccination experiment suggests that exposure to a related infection can protect against smallpox.", actualOutcome: "Vaccination becomes a major method of preventing infectious disease and helps eradicate smallpox.", domains: ["medicine", "science", "society"], demoNexusPrompt: "What if the early vaccination experiment was condemned and vaccination research was prohibited for fifty years?", imagePrompt: "A late-eighteenth-century medical study, physician examining vaccination materials, cautious witnesses, archival illustration, amber light, no readable text." },
  { id: "evt-003", year: 1853, title: "India's First Passenger Railway", description: "A passenger train travels from Bombay to Thane, marking the beginning of a railway network on the subcontinent.", actualOutcome: "Railways reshape travel, trade, administration, migration and political connection across colonial India and later independent India.", domains: ["technology", "economy", "society", "politics"], demoNexusPrompt: "What if India's first passenger railway was delayed for thirty years by local resistance, financing failures and difficult terrain?", imagePrompt: "1853 western India railway departure with an early steam locomotive, passengers in period clothing, station staff and monsoon sky, cinematic archival realism, no readable text." },
  { id: "evt-004", year: 1905, title: "The Swadeshi Movement", description: "The partition of Bengal prompts a broad movement for indigenous goods, public organisation and political self-determination.", actualOutcome: "Swadeshi strengthens mass political participation, Indian enterprise and the language of economic self-reliance within the independence movement.", domains: ["politics", "economy", "society", "culture"], demoNexusPrompt: "What if the Swadeshi movement formed a durable cooperative manufacturing network that spread across India before the First World War?", imagePrompt: "1905 Bengal public meeting with handwoven cloth, students, shopkeepers and political organisers in period-appropriate dress, grounded cinematic archival realism, no readable text." },
  { id: "evt-004b", year: 1932, title: "The Emu Campaign", description: "Australian soldiers are deployed against crop-damaging emus, discovering that the birds are difficult to contain.", actualOutcome: "The episode becomes a comic historical reminder that military equipment does not guarantee control over a natural system.", domains: ["society", "military", "economy"], demoNexusPrompt: "What if the emu campaign led to an early national investment in ecological farming and wildlife management?", imagePrompt: "1930s Australian wheat fields with emus, a small military truck and frustrated farmers at dawn, realistic archival cinema, restrained amber tones, no text." },
  { id: "evt-005", year: 1947, title: "The Transistor", description: "A small solid-state device demonstrates that electronic signals can be amplified without bulky vacuum tubes.", actualOutcome: "Transistors underpin integrated circuits, computers, telecommunications and modern consumer electronics.", domains: ["science", "technology", "economy"], demoNexusPrompt: "What if semiconductor amplification was judged commercially useless and major laboratories continued investing only in vacuum-tube technology?", imagePrompt: "1940s electronics laboratory, researchers studying a point-contact transistor beside vacuum-tube equipment, cinematic scientific archive, amber-black treatment, no readable text." },
  { id: "evt-006", year: 1957, title: "Signal from Orbit", description: "The first artificial satellite broadcasts a radio signal from orbit around Earth.", actualOutcome: "Sputnik intensifies the space race and accelerates investment in satellites, rocketry and science education.", domains: ["science", "technology", "politics", "military"], demoNexusPrompt: "What if the launch vehicle exploded publicly and the satellite programme was suspended after the failure?", imagePrompt: "1950s launch complex at night, early satellite rocket, steel towers and tracking station, Cold War archival realism, no logos." },
  { id: "evt-007", year: 1962, title: "The Nuclear Stand-Down", description: "A confrontation involving nuclear-armed powers is de-escalated before direct military conflict begins.", actualOutcome: "The Cuban Missile Crisis ends through negotiation, reinforcing crisis communication and nuclear-risk management.", domains: ["politics", "military", "society"], demoNexusPrompt: "What if a local military commander acted without authorisation and initiated direct confrontation during the crisis?", imagePrompt: "Tense 1962 command room with analogue maps, officers and naval tracking displays, cinematic archival realism, no flags or readable text." },
  { id: "evt-008", year: 1969, title: "The First Network Message", description: "Two distant computers exchange data through an experimental packet-switched network.", actualOutcome: "ARPANET becomes a predecessor of the modern internet and demonstrates networked communication between computer systems.", domains: ["technology", "science", "economy", "society"], demoNexusPrompt: "What if the experimental network was classified permanently and civilian universities were prohibited from compatible networks?", imagePrompt: "1969 computer laboratory with room-sized computers, terminals and network cables, archival amber lighting, no readable text." },
  { id: "evt-008b", year: 1977, title: "The Golden Record", description: "A spacecraft carries sounds and images from Earth into deep space, turning a scientific mission into a small act of cosmic optimism.", actualOutcome: "The record becomes an enduring cultural symbol of how humans choose to represent themselves beyond Earth.", domains: ["science", "culture", "technology"], demoNexusPrompt: "What if the Golden Record included a public global call for contributions and sparked a sustained international space-culture programme?", imagePrompt: "1977 spacecraft assembly room with a gold phonograph record, engineers in period clothing and careful instruments, cinematic archival realism, no readable text." },
  { id: "evt-009", year: 1989, title: "The Web Proposal", description: "A proposal outlines a hypertext system for sharing research across a distributed network.", actualOutcome: "The World Wide Web makes internet publishing and navigation accessible on a global scale.", domains: ["technology", "science", "economy", "society"], demoNexusPrompt: "What if the web proposal was rejected and research networks remained closed institutional systems for two decades?", imagePrompt: "Late-1980s research office with monochrome terminal, network diagrams and paper files, cinematic archival realism, no readable text." },
  { id: "evt-010", year: 2020, title: "Global Pause", description: "A health crisis reorganises the rhythms of the planet.", actualOutcome: "The pandemic accelerates remote work, public-health coordination and digital service adoption.", domains: ["medicine", "society", "economy", "technology"], demoNexusPrompt: "What if early global disease surveillance triggered coordinated containment before international spread?", imagePrompt: "2020 public-health coordination room with maps, masked researchers and analogue-style amber monitors, documentary archival realism, no readable text." },
];

export const initialEvents: TimelineEvent[] = seeds.map((event, position) => ({ ...event, position, causalDependencies: ["Prior scientific and institutional knowledge", "Communication and distribution networks", "Investment in practical adoption"], historicalImpact: ["Changes institutional decision-making", "Creates durable technical and social effects", "Shapes later research and infrastructure"], nexusGuardrails: ["Preserve existing institutions and parallel research.", "Model counterforces and regional variation.", "Do not treat speculative outcomes as historical fact."] }));
